title: Hayden's first website attempt
author: Hayden Schilling
email: h.schilling@unsw.edu.au
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hayden's first attempt at building a website

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
